"""
Unified YouTube Stream API - Uses the exact same cookie fetching mechanism
Generates fresh cookies for every request and uses them with yt-dlp
"""

from flask import Flask, request, jsonify
import yt_dlp
import requests
import re
import os
import json
import time
import logging
import sys
import signal
import threading
from datetime import datetime, timedelta
from typing import Dict, Optional
import uuid

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('youtube_api.log'),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

app = Flask(__name__)

class YouTubeCookieFetcher:
    """Exact same cookie fetcher from the working script"""
    
    def __init__(self, cookie_file='cookies.txt'):
        """
        Initialize the cookie fetcher
        """
        self.cookie_file = cookie_file
        self.session = requests.Session()
        self.last_fetch_time = None
        self.current_cookies = None
        self.lock = threading.Lock()
        
    def get_headers(self) -> Dict:
        """Get realistic browser headers"""
        return {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate, br',
            'DNT': '1',
            'Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'Sec-Fetch-Dest': 'document',
            'Sec-Fetch-Mode': 'navigate',
            'Sec-Fetch-Site': 'none',
            'Sec-Fetch-User': '?1',
            'Cache-Control': 'max-age=0',
        }
    
    def save_cookies_netscape_format(self, cookies_dict: Dict, domain: str = ".youtube.com") -> Optional[str]:
        """
        Save cookies in Netscape format (cookies.txt format)
        Returns path to cookie file
        """
        try:
            # Calculate expiration (1 year from now for persistent cookies)
            expiration = int((datetime.now() + timedelta(days=365)).timestamp())
            
            # Create a unique filename for this cookie batch
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            unique_id = str(uuid.uuid4())[:8]
            cookie_file = f'cookies_{timestamp}_{unique_id}.txt'
            
            with open(cookie_file, 'w') as f:
                # Write header
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# https://curl.se/docs/http-cookies.html\n")
                f.write("# This file was generated by YouTube Cookie Fetcher\n")
                f.write(f"# Generated: {datetime.now().isoformat()}\n\n")
                
                # Write each cookie
                for name, value in cookies_dict.items():
                    # Determine if secure (HTTPS only)
                    secure = "TRUE" if name.startswith('__Secure') else "FALSE"
                    
                    # Write cookie line
                    f.write(f"{domain}\tTRUE\t/\t{secure}\t{expiration}\t{name}\t{value}\n")
                
                f.write("\n")
            
            logger.info(f"✅ Cookies saved in Netscape format to {cookie_file}")
            return cookie_file
            
        except Exception as e:
            logger.error(f"Failed to save cookies: {e}")
            return None
    
    def fetch_cookies(self) -> Optional[Dict]:
        """
        Fetch fresh cookies from YouTube
        """
        try:
            logger.info("🌐 Fetching fresh cookies from YouTube...")
            
            # Clear previous cookies
            self.session.cookies.clear()
            
            # Make request to YouTube
            response = self.session.get(
                'https://www.youtube.com',
                headers=self.get_headers(),
                timeout=15,
                allow_redirects=True
            )
            
            if response.status_code != 200:
                logger.error(f"Failed to fetch YouTube. Status: {response.status_code}")
                return None
            
            # Get cookies from session
            cookies_dict = self.session.cookies.get_dict()
            
            if not cookies_dict:
                logger.warning("No cookies received")
                return None
            
            # Create cookie data
            cookie_data = {
                'timestamp': datetime.now().isoformat(),
                'timestamp_epoch': int(time.time()),
                'cookies': cookies_dict,
                'cookie_count': len(cookies_dict),
                'status_code': response.status_code
            }
            
            logger.info(f"✅ Successfully fetched {len(cookies_dict)} cookies")
            return cookie_data
            
        except requests.exceptions.Timeout:
            logger.error("Request timeout")
        except requests.exceptions.ConnectionError:
            logger.error("Connection error")
        except requests.exceptions.RequestException as e:
            logger.error(f"Request error: {e}")
        except Exception as e:
            logger.error(f"Unexpected error: {e}")
        
        return None
    
    def verify_cookies(self, cookie_data: Dict) -> bool:
        """Verify if cookies are valid"""
        try:
            test_session = requests.Session()
            
            # Set cookies
            for name, value in cookie_data['cookies'].items():
                test_session.cookies.set(name, value)
            
            # Test request
            response = test_session.get(
                'https://www.youtube.com',
                headers=self.get_headers(),
                timeout=10
            )
            
            if response.status_code == 200:
                logger.info("✅ Cookies verified and working")
                return True
            else:
                logger.warning(f"⚠️ Cookie verification failed. Status: {response.status_code}")
                return False
                
        except Exception as e:
            logger.error(f"Verification error: {e}")
            return False
    
    def get_fresh_cookie_file(self) -> Optional[str]:
        """
        Get a fresh cookie file for immediate use
        This is the main method to call for each request
        """
        with self.lock:
            # Fetch fresh cookies
            cookie_data = self.fetch_cookies()
            
            if not cookie_data:
                return None
            
            # Verify cookies
            if not self.verify_cookies(cookie_data):
                logger.warning("Cookie verification failed, but will try to use them anyway")
            
            # Save to file and return path
            cookie_file = self.save_cookies_netscape_format(cookie_data['cookies'])
            
            # Store current cookies
            self.current_cookies = cookie_data
            self.last_fetch_time = datetime.now()
            
            return cookie_file

def extract_video_id(url_or_id):
    """Extract YouTube video ID from URL or return the ID if already clean"""
    if re.match(r'^[a-zA-Z0-9_-]{11}$', url_or_id):
        return url_or_id
    
    patterns = [
        r'(?:youtube\.com\/watch\?v=)([^&]+)',
        r'(?:youtu\.be\/)([^?]+)',
        r'(?:youtube\.com\/embed\/)([^?]+)',
        r'(?:youtube\.com\/v\/)([^?]+)'
    ]
    
    for pattern in patterns:
        match = re.search(pattern, url_or_id)
        if match:
            return match.group(1)
    
    return None

def cleanup_old_cookie_files(max_age_minutes=5):
    """
    Clean up old cookie files
    """
    try:
        current_time = time.time()
        for filename in os.listdir('.'):
            if filename.startswith('cookies_') and filename.endswith('.txt'):
                file_path = os.path.join('.', filename)
                file_age = current_time - os.path.getmtime(file_path)
                
                # Delete files older than max_age_minutes
                if file_age > (max_age_minutes * 60):
                    try:
                        os.unlink(file_path)
                        logger.debug(f"Cleaned up old cookie file: {filename}")
                    except Exception as e:
                        logger.warning(f"Failed to delete {filename}: {e}")
    except Exception as e:
        logger.error(f"Cleanup error: {e}")

# Initialize the cookie fetcher
cookie_fetcher = YouTubeCookieFetcher()

@app.route('/stream', methods=['GET'])
def get_stream():
    """
    Main endpoint - generates fresh cookies and returns stream URL
    Usage: /stream?id=VIDEO_ID_OR_URL&format=FORMAT_ID
    """
    # Get parameters
    video_id = request.args.get('id')
    format_id = request.args.get('format', 'best')
    
    if not video_id:
        return jsonify({
            'success': False,
            'error': 'Missing id parameter',
            'usage': {
                'endpoint': '/stream?id=VIDEO_ID&format=FORMAT_ID',
                'examples': {
                    'get_360p': '/stream?id=p7ZG_xWYLzI&format=18',
                    'get_720p': '/stream?id=p7ZG_xWYLzI&format=22',
                    'get_best': '/stream?id=p7ZG_xWYLzI&format=best',
                    'get_audio_only': '/stream?id=p7ZG_xWYLzI&format=bestaudio'
                }
            }
        }), 400
    
    # Extract clean video ID
    clean_id = extract_video_id(video_id)
    if not clean_id:
        return jsonify({
            'success': False,
            'error': 'Invalid video ID or URL'
        }), 400
    
    # Generate a request ID for tracking
    request_id = str(uuid.uuid4())[:8]
    logger.info(f"[{request_id}] Processing request for video: {clean_id}, format: {format_id}")
    
    cookie_file = None
    start_time = time.time()
    
    try:
        # Get fresh cookies for this request
        cookie_file = cookie_fetcher.get_fresh_cookie_file()
        
        if not cookie_file:
            return jsonify({
                'success': False,
                'request_id': request_id,
                'error': 'Failed to generate cookies'
            }), 500
        
        # Configure yt-dlp with fresh cookies
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'extract_flat': False,
            'cookiefile': cookie_file,
            'format': format_id,
            'headers': {
                'Referer': 'https://www.youtube.com/',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
            },
            'extractor_args': {
                'youtube': {
                    'skip': ['dash', 'translated_subs'],
                    'player_client': ['android', 'web']
                }
            }
        }
        
        video_url = f'https://www.youtube.com/watch?v={clean_id}'
        
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            logger.info(f"[{request_id}] Extracting info with fresh cookies")
            info = ydl.extract_info(video_url, download=False)
            
            # Find the stream URL
            stream_url = None
            format_info = None
            
            # Try to get URL from formats list
            if 'formats' in info:
                for f in info['formats']:
                    if f.get('format_id') == format_id and f.get('url'):
                        stream_url = f['url']
                        format_info = {
                            'format_id': f.get('format_id'),
                            'ext': f.get('ext'),
                            'resolution': f.get('resolution') or f.get('format_note') or 'N/A',
                            'filesize': f.get('filesize'),
                            'vcodec': f.get('vcodec', 'none'),
                            'acodec': f.get('acodec', 'none')
                        }
                        break
            
            # If not found in formats, try the main URL
            if not stream_url and 'url' in info:
                stream_url = info['url']
                format_info = {
                    'format_id': format_id,
                    'ext': info.get('ext', 'unknown'),
                    'resolution': 'best'
                }
            
            if stream_url:
                elapsed_time = time.time() - start_time
                logger.info(f"[{request_id}] Success - Time: {elapsed_time:.2f}s")
                
                return jsonify({
                    'success': True,
                    'stream_url': stream_url,
                    'video_id': clean_id,
                    'title': info.get('title'),
                    'duration': info.get('duration'),
                    'uploader': info.get('uploader'),
                    'format': format_info,
                    'format_requested': format_id,
                    'view_count': info.get('view_count'),
                    'like_count': info.get('like_count'),
                    'request_id': request_id,
                    'processing_time': round(elapsed_time, 2),
                    'cookies_used': cookie_file
                })
            else:
                # Get available formats
                available_formats = []
                if 'formats' in info:
                    for f in info['formats'][:10]:  # Limit to 10 formats
                        available_formats.append({
                            'format_id': f.get('format_id'),
                            'ext': f.get('ext'),
                            'resolution': f.get('resolution') or f.get('format_note') or 'N/A',
                            'has_video': f.get('vcodec') != 'none',
                            'has_audio': f.get('acodec') != 'none'
                        })
                
                elapsed_time = time.time() - start_time
                return jsonify({
                    'success': False,
                    'error': f'Format {format_id} not available',
                    'available_formats': available_formats,
                    'title': info.get('title'),
                    'request_id': request_id,
                    'processing_time': round(elapsed_time, 2)
                }), 404
    
    except Exception as e:
        error_msg = str(e)
        error_msg = re.sub(r'\x1b\[[0-9;]*m', '', error_msg)
        logger.error(f"[{request_id}] Error: {error_msg}")
        
        elapsed_time = time.time() - start_time
        return jsonify({
            'success': False,
            'error': error_msg,
            'request_id': request_id,
            'processing_time': round(elapsed_time, 2)
        }), 500
    
    finally:
        # Clean up old cookie files periodically (not the one we just used)
        if request_id and int(request_id[:2], 16) % 10 == 0:  # Random cleanup
            cleanup_old_cookie_files()

@app.route('/info', methods=['GET'])
def get_info():
    """
    Get video information without stream URL
    Usage: /info?id=VIDEO_ID_OR_URL
    """
    video_id = request.args.get('id')
    
    if not video_id:
        return jsonify({
            'success': False,
            'error': 'Missing id parameter'
        }), 400
    
    clean_id = extract_video_id(video_id)
    if not clean_id:
        return jsonify({
            'success': False,
            'error': 'Invalid video ID or URL'
        }), 400
    
    request_id = str(uuid.uuid4())[:8]
    cookie_file = None
    start_time = time.time()
    
    try:
        # Get fresh cookies for this request
        cookie_file = cookie_fetcher.get_fresh_cookie_file()
        
        if not cookie_file:
            return jsonify({
                'success': False,
                'request_id': request_id,
                'error': 'Failed to generate cookies'
            }), 500
        
        # Configure yt-dlp
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'extract_flat': False,
            'cookiefile': cookie_file,
            'headers': {
                'Referer': 'https://www.youtube.com/',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
            }
        }
        
        video_url = f'https://www.youtube.com/watch?v={clean_id}'
        
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(video_url, download=False)
            
            # Extract format information
            formats = []
            if 'formats' in info:
                for f in info['formats']:
                    formats.append({
                        'format_id': f.get('format_id'),
                        'ext': f.get('ext'),
                        'resolution': f.get('resolution') or f.get('format_note') or 'N/A',
                        'filesize_mb': round(f.get('filesize', 0) / (1024 * 1024), 2) if f.get('filesize') else None,
                        'has_video': f.get('vcodec') != 'none',
                        'has_audio': f.get('acodec') != 'none',
                        'fps': f.get('fps'),
                        'vcodec': f.get('vcodec'),
                        'acodec': f.get('acodec')
                    })
            
            elapsed_time = time.time() - start_time
            return jsonify({
                'success': True,
                'request_id': request_id,
                'video_id': clean_id,
                'title': info.get('title'),
                'duration': info.get('duration'),
                'uploader': info.get('uploader'),
                'view_count': info.get('view_count'),
                'like_count': info.get('like_count'),
                'description': info.get('description')[:500] + '...' if info.get('description') and len(info.get('description')) > 500 else info.get('description'),
                'thumbnail': info.get('thumbnail'),
                'upload_date': info.get('upload_date'),
                'formats': formats,
                'format_count': len(formats),
                'processing_time': round(elapsed_time, 2)
            })
    
    except Exception as e:
        error_msg = re.sub(r'\x1b\[[0-9;]*m', '', str(e))
        elapsed_time = time.time() - start_time
        return jsonify({
            'success': False,
            'request_id': request_id,
            'error': error_msg,
            'processing_time': round(elapsed_time, 2)
        }), 500
    
    finally:
        # Clean up
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.unlink(cookie_file)
                logger.debug(f"[{request_id}] Cleaned up cookie file: {cookie_file}")
            except:
                pass

@app.route('/', methods=['GET'])
def home():
    """Home endpoint with usage instructions"""
    return jsonify({
        'name': 'Unified YouTube Stream API',
        'version': '1.0.0',
        'description': 'Uses exact same cookie fetching mechanism from working script',
        'endpoints': {
            'get_stream': {
                'url': '/stream?id=VIDEO_ID&format=FORMAT_ID',
                'description': 'Get streaming URL with fresh cookies',
                'examples': {
                    '360p': '/stream?id=p7ZG_xWYLzI&format=18',
                    '720p': '/stream?id=p7ZG_xWYLzI&format=22',
                    '1080p': '/stream?id=p7ZG_xWYLzI&format=137',
                    'best': '/stream?id=p7ZG_xWYLzI&format=best',
                    'audio': '/stream?id=p7ZG_xWYLzI&format=bestaudio'
                }
            },
            'get_info': {
                'url': '/info?id=VIDEO_ID',
                'description': 'Get video information and available formats',
                'example': '/info?id=p7ZG_xWYLzI'
            }
        },
        'common_format_ids': {
            '18': '360p (MP4)',
            '22': '720p (MP4)',
            '137': '1080p (video only)',
            '140': 'Audio only (M4A)',
            '251': 'Audio only (OPUS)',
            'best': 'Best quality',
            'bestaudio': 'Best audio only',
            'worst': 'Worst quality'
        }
    })

@app.errorhandler(404)
def not_found(e):
    return jsonify({
        'success': False,
        'error': 'Endpoint not found',
        'available_endpoints': ['/', '/stream', '/info']
    }), 404

def signal_handler(signum, frame):
    """Handle shutdown signals"""
    logger.info("Shutdown signal received. Cleaning up...")
    
    # Clean up all cookie files on shutdown
    try:
        for filename in os.listdir('.'):
            if filename.startswith('cookies_') and filename.endswith('.txt'):
                try:
                    os.unlink(filename)
                    logger.info(f"Cleaned up: {filename}")
                except:
                    pass
    except Exception as e:
        logger.error(f"Cleanup error on shutdown: {e}")
    
    sys.exit(0)

if __name__ == '__main__':
    # Setup signal handlers
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    
    print("=" * 60)
    print("🚀 Unified YouTube Stream API")
    print("=" * 60)
    print("Features:")
    print("  • Uses EXACT same cookie fetching mechanism from working script")
    print("  • Fresh cookies generated for EVERY request")
    print("  • Automatic cleanup of old cookie files")
    print("\nEndpoints:")
    print("  • GET /stream?id=VIDEO_ID&format=FORMAT")
    print("  • GET /info?id=VIDEO_ID")
    print("\nExamples:")
    print("  • http://localhost:5000/stream?id=p7ZG_xWYLzI&format=18")
    print("  • http://localhost:5000/info?id=p7ZG_xWYLzI")
    print("=" * 60)
    
    # Run the app
    app.run(host='0.0.0.0', port=5000, debug=True, threaded=True)
